name: Release Tag Creator

on:
 pull_request:
    types:
      - closed
      
permissions:
  contents: write 
  
jobs:
  base-branch-release:
    if: ${{ startsWith(github.event.pull_request.base.ref, 'release/') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out Head Branch
        uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.ref }}

      - name: Head Branch 커밋 내역 추출
        run: |
         HEAD_SHA=${{ github.event.pull_request.head.sha }}
         echo "$HEAD_SHA" >> $GITHUB_ENV
         
      - name: Check out Base Branch
        uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.base.ref }}

      - name: Base Branch 커밋 내역 추출
        run: |
         BASE_SHA=${{ github.event.pull_request.base.sha }}
         echo "$BASE_SHA" >> $GITHUB_ENV
          
      - name: 버전 정보 추출
        run: |
          echo "Release 브랜치에서 앱 버전 정보를 가져옵니다."
          PR_VERSION_NAME=$(grep -oP '(?<=versionName\s=\s").*?(?=")' app/build.gradle.kts)
          echo "PR_VERSION_NAME=$PR_VERSION_NAME" >> $GITHUB_ENV

      - name: 릴리즈 노트 (커밋 사안들) 생성
        run: |
          git fetch origin $BASE_SHA $HEAD_SHA
          CHANGES=$(git log --oneline --no-merges ${{ env.BASE_SHA }}..${{ HEAD_SHA }} )
          echo "## What's Changed" > release_notes.md
          echo "$CHANGES" >> release_notes.md
          echo "RELEASE_BODY=$(cat release_notes.md)" >> $GITHUB_ENV

      - name: 깃허브 릴리즈 태그 생성
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ env.PR_VERSION_NAME }} 
          release_name: Release ${{ env.PR_VERSION_NAME }} 
          body: ${{ env.RELEASE_BODY }}
