name: Release Tag Creator

on:
 pull_request:
    types:
      - closed
      
permissions:
  contents: write 
  
jobs:
  base-branch-release:
    if: ${{ startsWith(github.event.pull_request.base.ref, 'release/') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Base 및 Head Sha 가져옴
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git fetch origin ${{ github.event.pull_request.head.sha }}
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          
      - name: Base Branch 로 체크아웃
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          
      - name: 버전 정보 추출
        run: |
          echo "Release 브랜치에서 앱 버전 정보를 가져옵니다."
          PR_VERSION_NAME=$(grep -oP '(?<=versionName\s=\s").*?(?=")' app/build.gradle.kts)
          echo "PR_VERSION_NAME=$PR_VERSION_NAME" >> $GITHUB_ENV

      - name: 릴리즈 노트 (커밋 사안들) 생성
        run: |
          CHANGES=$(git log --oneline --no-merges ${{ env.BASE_SHA }}..${{ env.HEAD_SHA }} )
          RELEASE_BODY="## What's Changed"$'\n\n'"$CHANGES"
          echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV

      - name: 깃허브 릴리즈 태그 생성
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ env.PR_VERSION_NAME }} 
          release_name: Release ${{ env.PR_VERSION_NAME }} 
          body: ${{ env.RELEASE_BODY }}
